# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-10 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名字')),
                ('url', models.CharField(max_length=256, verbose_name='地址')),
                ('target', models.CharField(choices=[('0', '背景'), ('1', '头像')], max_length=8, verbose_name='用途标记')),
                ('class_target', models.CharField(default=0, max_length=8, verbose_name='分类标记')),
            ],
        ),
    ]
